Configuration As screen:

    Icon2_3 As icon.OptionsList:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(255, 255, 255, 1)
        Icon: =Icon.OptionsList
        Width: =87
        X: =6
        Y: =8
        ZIndex: =1

    Label5_1 As label:
        Height: =122
        Size: =50
        Text: ="Configuration"
        Width: =463
        X: =93
        Y: =33
        ZIndex: =2

    Label8 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Follow and invite friends"
        Width: =560
        X: =33
        Y: =172
        ZIndex: =3

    Label8_1 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Notification"
        Width: =560
        X: =33
        Y: =237
        ZIndex: =4

    Label8_2 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Privacity"
        Width: =560
        X: =33
        Y: =304
        ZIndex: =5

    Label8_3 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Segurity"
        Width: =560
        X: =33
        Y: =370
        ZIndex: =6

    Label8_4 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Ads"
        Width: =560
        X: =33
        Y: =433
        ZIndex: =7

    Label8_5 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Lenguage"
        Width: =560
        X: =33
        Y: =497
        ZIndex: =8

    Label8_6 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Account"
        Width: =560
        X: =33
        Y: =564
        ZIndex: =9

    Label8_7 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="About"
        Width: =560
        X: =33
        Y: =635
        ZIndex: =10

    Label8_8 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Help"
        Width: =560
        X: =33
        Y: =706
        ZIndex: =11

    Label8_9 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Height: =47
        Size: =21
        Text: ="Topics"
        Width: =560
        X: =33
        Y: =774
        ZIndex: =12

    Label8_10 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        Height: =47
        Size: =21
        Text: ="Add account"
        Width: =560
        X: =33
        Y: =874
        ZIndex: =13

    Label8_11 As label:
        BorderColor: =RGBA(0, 0, 0, 1)
        Height: =47
        Size: =21
        Text: ="Exit all accounts"
        Width: =560
        X: =33
        Y: =933
        ZIndex: =14

    Icon15 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =179
        ZIndex: =15

    Icon15_1 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =310
        ZIndex: =16

    Icon15_2 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =378
        ZIndex: =17

    Icon15_3 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =440
        ZIndex: =18

    Icon15_4 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =243
        ZIndex: =19

    Icon15_5 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =642
        ZIndex: =20

    Icon15_6 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =712
        ZIndex: =21

    Icon15_7 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =780
        ZIndex: =22

    Icon15_8 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =503
        ZIndex: =23

    Icon15_9 As icon.ChevronRight:
        Color: =RGBA(0, 0, 0, 1)
        Height: =34
        Icon: =Icon.ChevronRight
        Width: =38
        X: =543
        Y: =570
        ZIndex: =24

